// <auto-generated />
namespace ASM2MVC.EF.SystemMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FPTSystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FPTSystem));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071405283_FPTSystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
